Client Service
IIExpanse/taxi-service pull request #1
Opened 2024-01-04 19:03 UTC by nedhermi

2024-01-07 17:14 UTC, IIExpanse requested changes
Привет)
В целом все неплохо. Понравилась практика с группированием тестов по вложенным классам - еще не встречался с такой.
Рассмотри возможность расширить использование мапструкта - сейчас при создании и обновлении объектов значения переносятся вручную, что может быть довольно неудобно при частых изменениях классов и большой кодовой базе (везде придется править вручную).
Еще посмотри, как поднимать в спринге тестовую БД и работать с ней в тестах - очень пригодится при тестировании слоя репозиториев и интеграционных тестах. Плюс не надо будет отдельно поднимать свою базу.

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/main/java/clientservice/dto/ClientResponseDto.java
> +public class ClientResponseDto {
Можно создать один класс ResponseDto и, при возврате, наполнять его только необходимыми полями.
Необходимые поля можно определить в мапструкте через ignore, пример можно посмотреть здесь https://github.com/IIExpanse/java-explore-with-me/blob/main/ewm-service/src/main/java/ru/yandex/practicum/ewm/event/mapper/EventMapper.java.

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/main/java/clientservice/handler/CustomHandler.java
> +
Местами есть лишние пустые строки, стоит отформатировать.

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/main/java/clientservice/service/ClientService.java
> +                .build();
Маппинг значений в новую сущность может взять на себя мапструкт, необязательно делать это вручную отдельно для каждого поля.
Пример можно посмотреть здесь: https://github.com/IIExpanse/java-explore-with-me/blob/main/ewm-service/src/main/java/ru/yandex/practicum/ewm/event/mapper/EventMapper.java

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/main/java/clientservice/service/ClientService.java
> +        client.setLogin(clientRequestDto.getLogin());
С обновлением полей аналогично можно использовать мапструкт, чтобы избавиться от ручной работы.
Для обозначения целевого объекта, в который мапятся значения, используется аннотация @MappingTarget, а для игнорирования null полей (чтобы не заменять актуальные значения на null при частичном обновлении) можно прописать nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE в аннотации @Mapper.
Пример можно посмотреть здесь: https://github.com/IIExpanse/java-explore-with-me/blob/main/ewm-service/src/main/java/ru/yandex/practicum/ewm/event/mapper/EventMapper.java

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/main/java/clientservice/entities/Client.java
> +@Data
Автосгенерированные equals и hashcode (которые входят в @ Data) могут вызвать проблемы при работе с Hibernate, идея прямо пишет "Using @ Data for JPA entities is not recommended. It can cause severe performance and memory consumption issues. " и предлагает автоматически сгенерировать безопасный вариант методов для работы с Hibernate.

2024-01-07 17:14 UTC, IIExpanse commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
Сейчас интеграционные тесты работают только при наличии подключения к реальной БД.
Spring можно настроить, чтобы он поднимал тебе в памяти тестовую базу и сам же ее чистил. Параметры тестовой базы ты определяешь в .properties, которые лежат в тестовой директории, как здесь: https://github.com/IIExpanse/java-explore-with-me/blob/main/ewm-service/src/test/resources/application.properties

В итоге ты избавишься от зависимости тестов от БД, и не придется очищать базу вручную.
Посмотри здесь на аннотации @AutoConfigureTestDatabase и @DirtiesContext, которые используются для автоконфигурации базы и очистки контекста: https://github.com/IIExpanse/java-explore-with-me/blob/main/ewm-service/src/test/java/ru/yandex/practicum/ewm/event/service/EventServiceTest.java

2024-01-07 18:07 UTC, nedhermi commented on client-service/src/main/java/clientservice/dto/ClientResponseDto.java
> +public class ClientResponseDto {
И через рефлексию можно получить доступ к скрытым данным. Дто оно и есть, data transfer object. Объект для передачи.

2024-01-07 18:09 UTC, nedhermi commented on client-service/src/main/java/clientservice/dto/ClientResponseDto.java
> +public class ClientResponseDto {
Я придерживаюсь мнения, что ДТО объекты должны иметь только те данные которые необходимы для функционала.

2024-01-07 18:10 UTC, nedhermi commented on client-service/src/main/java/clientservice/handler/CustomHandler.java
> +
Думаю это не критично, у нас нет контракта по которому мы пишем код.

2024-01-07 18:13 UTC, nedhermi commented on client-service/src/main/java/clientservice/service/ClientService.java
> +                .build();
Я пользовался ломбок, и создавал сущность в ручную. Так читаемость кода лучше, чем мап стракшн.

2024-01-07 18:14 UTC, nedhermi commented on client-service/src/main/java/clientservice/service/ClientService.java
> +        client.setLogin(clientRequestDto.getLogin());
Аналогично, я не буду переделывать. У нас контракт не прописан, что сущности должны создаваться через конвертацию.

2024-01-07 18:26 UTC, nedhermi commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
Я хочу пользоваться postgresql и у меня в пропертях  настроено автоматическое подключение  к базе данных postgresql. 
Локально через команду docker-compose up -d я подымаю бд. Ямл файл есть в проекте. На гитхабе в CI настроено автоматическое поднятие бд postgresql. Не вижу проблем. Мой выбор postgresql а не h2. Вроде в ДЗ postgres нужно использовать.

2024-01-07 19:12 UTC, IIExpanse commented on client-service/src/main/java/clientservice/dto/ClientResponseDto.java
> +public class ClientResponseDto {
Не очень понял про рефлексию, невостребованные поля не будут мапиться и будут содержать null.

2024-01-07 19:12 UTC, IIExpanse commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
Тут речь о тестовых пропертях. 
Основные проперти менять не надо, рабочая база останется той же.

2024-01-07 19:57 UTC, nedhermi commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
У меня локально и на CI работает. В чем проблема? И да, есть такие запросы, что на другой бд не протестируешь.

2024-01-07 20:47 UTC, IIExpanse commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
В данном случае таких запросов нет, тем более все идет через hibernate.
Основная проблема в том, что для внутренних тестов приложения в данном случае нужно что-то, помимо самого приложения.

Но твоя позиция мне понятна, правок не жду.
PR пока будет открыт. После праздников узнаю, будет ли Максим проверять проекты помодульно. Если будет, то запрошу еще его ревью.
Если нет, ветка будет смержена как есть.

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/controller/ClientController.java
> +import org.springframework.web.bind.annotation.*;
импорт со звездочкой нужно убрать

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/entities/Client.java
> +@Data
Согласен, лучше отказаться от использования equals и hashcode в `@Data`

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/entities/Client.java
> +    private Integer id;
Хотя бы Long

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/handler/CustomHandler.java
> +
Нужно следить не только за правильностью написания кода, но и за его стилем. Дополнительные пустые строки не есть хорошая практика.

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/dto/ClientRequestDto.java
> +@SuperBuilder
`@SuperBuilder` если нету наследования, то эта аннотация не нужна

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/dto/ClientRequestDto.java
> +@Data
`@Data` под капотом содержит кучу других аннотаций. Поэтому лучше использовать только то, что нужно

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/handler/CustomHandler.java
> +    public String handleNotFound(NotFoundException e) {
При NotFoundException хорошо сделать более расширенный ответ
https://habr.com/ru/articles/528116/

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/service/ClientService.java
> +                .build();
Mapstruct у нас прописан в ДЗ и с ним нужно поработать

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/dto/ClientResponseDto.java
> +public class ClientResponseDto {
По ДЗ используем record

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/service/ClientService.java
> +        val client = Client.builder()
Эта логика должна быть в маппере

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/service/ClientService.java
> +        client.setLogin(clientRequestDto.getLogin());
Прописано в ДЗ про MapStruct)

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/time/DateTimeProvider.java
> +
Лишняя строка

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/time/DateTimeProvider.java
> +public class DateTimeProvider {
В целом ненужный класс. Не вижу необходимости создавать новый бин для методов с логикой в одну строку

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/resources/application.properties
> +spring.datasource.password=root
пароль лучше сгенерировать более сложный

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/test/java/clientservice/repository/ClientRepositoryTest.java
> +@Sql("/db/RESET_AUTO_INCREMENT.sql")
Тесты не должны работать с реальной БД. А если там крупные суммы денег, то ошибка в тестах может привести к самым плохим последствиям. В данном случае нужно применять тест-контейнеры или БД In-memory

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/converters/ClientToClientResponseDtoConverter.java
> +package clientservice.converters;
Согласно ДЗ:
```java
package clientservice.mapper;
```

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/converters/ClientToClientResponseDtoConverter.java
> +    ClientResponseDto convert(final Client client);
```java
ClientResponseDto toClientResponseDto(Client client);
```

2024-01-20 20:43 UTC, developer-aston commented on client-service/src/main/java/clientservice/entities/Client.java
> +    private Instant createdAt;
Лучше LocalDate

2024-01-21 17:00 UTC, IIExpanse approved these changes

2024-01-21 17:00 UTC, merged